#!/bin/bash
SAVE=true    # assign true to preserve workdirs

INPUTDIR=`pwd -P`/input
test -s "$EXECPDC_JOBE_RUNS" ||
    eval `grep EXECPDC_JOBE_RUNS execpdc.config`
cd "$EXECPDC_JOBE_RUNS"

for INFILE in trap-omp.cpp mpi_spmd.c cuda_device_info.cu cuda_dim3Demo.cu 
do  echo ===== $INFILE
    WORKDIR=execpdc_`basename $INFILE | sed 's/\..*//'`_`date +%s.%3N`
    mkdir $WORKDIR || {
	echo "Could not create workdir $WORKDIR, aborting"
	exit 1
    }
    cp $INPUTDIR/$INFILE $WORKDIR/EXECPDC_INPUT
    EXECPDC_SERVER=localhost ./execpdc $WORKDIR EXECPDC_INPUT
    echo ""
    $SAVE || rm -rf $WORKDIR
done
