#!/bin/bash
SAVE=false    # assign true to preserve workdirs

BINDIR=`pwd -P`
INPUTDIR=$BINDIR/input
if test -s "$EXECPDC_JOBE_RUNS"
then cd "$EXECPDC_JOBE_RUNS"
else eval `grep JOBE_RUNS execpdc.config`
     cd $JOBE_RUNS
fi

for INFILE in trap-omp.cpp mpi_spmd.c cuda_device_info.cu cuda_dim3Demo.cu 
do  echo ===== $INFILE
    WORKDIR=execpdc_`basename $INFILE | sed 's/\..*//'`_`date +%s.%3N`
    mkdir $WORKDIR || {
	echo "Could not create workdir $WORKDIR, aborting"
	exit 1
    }
    cp $INPUTDIR/$INFILE $WORKDIR/EXECPDC_INPUT
    EXECPDC_SERVER=localhost $BINDIR/execpdc $WORKDIR EXECPDC_INPUT
    echo ""
    $SAVE || rm -rf $WORKDIR
done
