#!/bin/bash
# perform some test runs of execpdc from command line
SAVE=false    # assign true to preserve workdirs

BINDIR=`pwd -P`
INPUTDIR=$BINDIR/input
if test -s "$EXECPDC_JOBE_DIR"
then cd "$EXECPDC_JOBE_DIR"
else eval `grep -m 1 JOBE_DIR execpdc.config || echo false` &&
	cd $JOBE_DIR || {
	    echo "JOBE_DIR not defined in execpdc.config, aborting"
	    exit 1
	}
fi

for INFILE in trap-omp.cpp mpi_spmd.c cuda_device_info.cu cuda_dim3Demo.cu 
do  echo ===== $INFILE
    WORKDIR=execpdc_`basename $INFILE | sed 's/\..*//'`_`date +%s.%3N`
    mkdir $WORKDIR || {
	echo "Could not create workdir $WORKDIR, aborting"
	exit 1
    }
    cp $INPUTDIR/$INFILE $WORKDIR/EXECPDC_INPUT
    EXECPDC_SERVER=localhost $BINDIR/execpdc $WORKDIR EXECPDC_INPUT
    echo ""
    $SAVE || rm -rf $WORKDIR
done
